package old.games_swing.GameLogic;

import old.games_swing.Games.Maze.Maze_2D.MazeGui;
import old.games_swing.Games.Maze.Maze_3D.Maze3D_GUI;
import old.games_swing.Games.Memory.Memory;
import old.games_swing.Games.Minesweeper.Minesweeper;
import old.games_swing.Games.PingPong.PingPong;
import old.games_swing.Games.Sudoku.SudokuGui;
import old.games_swing.Games.TicTacToe.TicTacToe;
import old.games_swing.Games.fourInRow.FourInRow;
import old.games_swing.Games.g2048.g2048Gui;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * Frame where you can select witch Game you will play
 *
 * @author Elias
 */
public class GamesAuswahl extends javax.swing.JFrame {

    /**
     * Creates new form GamesAuswahl with the battlefield Icon
     */
    public GamesAuswahl() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("battlefield.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        cmdMinesweeperDeluxe = new javax.swing.JButton();
        cmdPingPong = new javax.swing.JButton();
        cmd2048 = new javax.swing.JButton();
        cmdMemory = new javax.swing.JButton();
        cmdMaze = new javax.swing.JButton();
        cmdFourInRow = new javax.swing.JButton();
        cmdSudoku = new javax.swing.JButton();
        cmdTicTacToe = new javax.swing.JButton();
        cmdMaze1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(0, 204, 0));
        backgroundPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        cmdMinesweeperDeluxe.setBackground(new java.awt.Color(0, 0, 204));
        cmdMinesweeperDeluxe.setForeground(new java.awt.Color(255, 255, 255));
        cmdMinesweeperDeluxe.setText("Minesweeper Deluxe");
        cmdMinesweeperDeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinesweeperDeluxeKlick(evt);
            }
        });

        cmdPingPong.setBackground(new java.awt.Color(204, 0, 204));
        cmdPingPong.setForeground(new java.awt.Color(255, 255, 255));
        cmdPingPong.setText("Ping Pong");
        cmdPingPong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPingPongMinesweeperKlick(evt);
            }
        });

        cmd2048.setBackground(new java.awt.Color(204, 0, 0));
        cmd2048.setForeground(new java.awt.Color(255, 255, 255));
        cmd2048.setText("2048");
        cmd2048.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd2048Klick(evt);
            }
        });

        cmdMemory.setBackground(new java.awt.Color(0, 102, 51));
        cmdMemory.setForeground(new java.awt.Color(255, 255, 255));
        cmdMemory.setText("Memory");
        cmdMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMemoryKlick(evt);
            }
        });

        cmdMaze.setBackground(new java.awt.Color(153, 255, 255));
        cmdMaze.setText("Maze 2D");
        cmdMaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMazeKlick(evt);
            }
        });

        cmdFourInRow.setBackground(new java.awt.Color(255, 51, 204));
        cmdFourInRow.setText("4 gewinnt");
        cmdFourInRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFourInRowKlick(evt);
            }
        });

        cmdSudoku.setBackground(new java.awt.Color(102, 255, 102));
        cmdSudoku.setText("Sudoku");
        cmdSudoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSudokuKlick(evt);
            }
        });

        cmdTicTacToe.setBackground(new java.awt.Color(0, 0, 204));
        cmdTicTacToe.setForeground(new java.awt.Color(255, 255, 255));
        cmdTicTacToe.setText("Tic Tac Toe");
        cmdTicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTicTacToeMinesweeperDeluxeKlick(evt);
            }
        });

        cmdMaze1.setBackground(new java.awt.Color(153, 255, 255));
        cmdMaze1.setText("Maze 3D");
        cmdMaze1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMaze1Klick(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdMinesweeperDeluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPingPong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd2048, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSudoku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFourInRow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMaze1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdMinesweeperDeluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdPingPong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmd2048, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdMaze, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdSudoku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdFourInRow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdTicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdMaze1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //opens an new Minesweeper Game.
    private void MinesweeperDeluxeKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinesweeperDeluxeKlick
        DefFrame frame = new DefFrame(300, 100, "Minesweeper");
        Minesweeper game = new Minesweeper(frame);
    }//GEN-LAST:event_MinesweeperDeluxeKlick
    //opens an new Ping Pong Game.
    private void cmdPingPongMinesweeperKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPingPongMinesweeperKlick
        DefFrame frame = new DefFrame(1000, 600, "Ping-Pong");
        frame.setMinimumSize(new Dimension(500, 250));
        PingPong game = new PingPong(frame);
        frame.add(game);
    }//GEN-LAST:event_cmdPingPongMinesweeperKlick
    //opens an new 2048 Game.
    private void cmd2048Klick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd2048Klick
        DefFrame frame = new DefFrame(500, 500, "2048");
        g2048Gui game = new g2048Gui(frame);
    }//GEN-LAST:event_cmd2048Klick
    //opens an new Memory Game.
    private void cmdMemoryKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMemoryKlick
        DefFrame frame = new DefFrame(600, 600, "Memory");
        Memory game = new Memory(frame);
        game.newGame();
    }//GEN-LAST:event_cmdMemoryKlick
    //opens an new Maze Game.
    private void cmdMazeKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMazeKlick
        DefFrame frame = new DefFrame(500, 500, "Maze");
        MazeGui game = new MazeGui(frame);
    }//GEN-LAST:event_cmdMazeKlick
    //opens an new Sudoku Game.
    private void cmdSudokuKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSudokuKlick
        DefFrame frame = new DefFrame(1000, 1000, "Sudoku");
        SudokuGui game = new SudokuGui(frame);
    }//GEN-LAST:event_cmdSudokuKlick
    //opens a new Four in a Row game
    private void cmdFourInRowKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFourInRowKlick
        DefFrame frame = new DefFrame(500, 500, "4 gewinnt");
        FourInRow game = new FourInRow(frame);
    }//GEN-LAST:event_cmdFourInRowKlick
    //opens a new Tic Tac Toe game
    private void cmdTicTacToeMinesweeperDeluxeKlick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTicTacToeMinesweeperDeluxeKlick
        DefFrame frame = new DefFrame(400, 400, "Tic Tac Toe");
        TicTacToe game = new TicTacToe(frame);
    }//GEN-LAST:event_cmdTicTacToeMinesweeperDeluxeKlick

    private void cmdMaze1Klick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMaze1Klick
       new Maze3D_GUI();
    }//GEN-LAST:event_cmdMaze1Klick

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cmd2048;
    private javax.swing.JButton cmdFourInRow;
    private javax.swing.JButton cmdMaze;
    private javax.swing.JButton cmdMaze1;
    private javax.swing.JButton cmdMemory;
    private javax.swing.JButton cmdMinesweeperDeluxe;
    private javax.swing.JButton cmdPingPong;
    private javax.swing.JButton cmdSudoku;
    private javax.swing.JButton cmdTicTacToe;
    // End of variables declaration//GEN-END:variables
}
